/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.board;

public class App {
  public static void main(String[] args) {
    System.out.println("[게시판 애플리케이션]");
    System.out.println("환영합니다!");
  }
}
